apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-install
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: {{ .Values.targetNamespace }}
    server: 'https://kubernetes.default.svc'

  sources:
    - repoURL: 'https://metallb.github.io/metallb'
      targetRevision: {{ .Values.version }}
      chart: metallb

    - repoURL: 'https://github.com/francisco1code/Helm-k8s'
      targetRevision: HEAD
      ref: values


  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace={{ .Values.createTargetNamespace }}
    automated:
      selfHeal: true
      prune: true
